name: seqzip
version: 0.1.0.0
synopsis: Sequent Calculus with Zippers
description: See readme.
maintainer: Xiaoshuang Yang <thuyxs17@gmail.com>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck
  - graphviz
  - temporary
  - bytestring
  - tagged
  - hspec
  - multiset
  - process
  - containers

library:
  source-dirs: lib

tests:
  Test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - seqzip
      - QuickCheck
      - hspec

benchmarks:
  runtime:
    source-dirs: bench
    main: runtime.hs
    dependencies:
      - base >= 4.8 && < 5
      - bytestring
      - cassava
      - criterion
      - directory
      - scientific
      - seqzip
      - split
      - vector
  memory:
    source-dirs: bench
    ghc-options: -rtsopts
    main: memory.hs
    dependencies:
      - base >= 4.8 && < 5
      - seqzip
      - weigh
