# thanks to https://github.com/rolandtritsch/haskell-aoc-2020

on: [push]

name: CI

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        key: stack
        path: |
          ~/.stack
          ~/.stack-work
    - uses: actions/checkout@v4
    - name: Compile all tests
      run: stack --system-ghc test --no-run-tests
    - name: "Run all tests"
      run: stack --system-ghc test
  build-benchmarks:
    name: Check that benchmarks compile
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        key: stack
        path: |
          ~/.stack
          ~/.stack-work
    - uses: actions/checkout@v4
    - name: Compile web interface
      run: stack --system-ghc bench --no-run-benchmarks
