# thanks to https://github.com/rolandtritsch/haskell-aoc-2020

on: [push]

name: CI

jobs:
  tests:
    name: Compile and run tests
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        key: stack
        path: |
          ~/.stack
          ~/.stack-work
    - uses: actions/checkout@v4
    - name: Compile tests
      run: stack --system-ghc test --no-run-tests
    - name: "Run tests"
      run: stack --system-ghc test
  build-benchmarks:
    name: Compile benchmarks
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        key: stack
        path: |
          ~/.stack
          ~/.stack-work
    - uses: actions/checkout@v4
    - name: Compile benchmarks
      run: stack --system-ghc bench --no-run-benchmarks
